### ISSUE TITLE
Not able to save the qgis project.

### ISSUE THREAD

**Issue by shanmugamg** [pka/qgpkg#16]
faced with this issue while testing qpgkg plugin

OS: Windows 10 x64
QGIS: 2.18.11 x64
qgpkg: 0.3

---
An error has occurred while executing Python code: 

NameError: global name 'reply' is not defined 
Traceback (most recent call last):
  File "C:/Users/ganesh/.qgis2/python/plugins\QgisGeopackage\qgis_geopackage.py", line 156, in write
    gpkg.write(project_path)
  File "C:/Users/ganesh/.qgis2/python/plugins\QgisGeopackage\qgpkg_qgis.py", line 120, in write
    if reply:
NameError: global name 'reply' is not defined

Python version: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
QGIS version: 2.18.11 Las Palmas, 29548e7 

Python Path:
C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python/plugins\processing
C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python
C:/Users/ganesh/.qgis2/python
C:/Users/ganesh/.qgis2/python/plugins
C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python/plugins
C:\PROGRA~1\QGIS2~1.18\bin\python27.zip
C:\PROGRA~1\QGIS2~1.18\apps\Python27\DLLs
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\plat-win
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\lib-tk
C:\PROGRA~1\QGIS2~1.18\bin
C:\PROGRA~1\QGIS2~1.18\apps\Python27
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\jinja2-2.7.2-py2.7.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\markupsafe-0.23-py2.7-win-amd64.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\win32
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\Pythonwin
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\Shapely-1.2.18-py2.7-win-amd64.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\wx-2.8-msw-unicode
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\xlrd-0.9.2-py2.7.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\xlwt-0.7.5-py2.7.egg
C:/Users/ganesh/.qgis2//python
C:\Users\ganesh\.qgis2\python\plugins\mmqgis/forms
D:/Dropbox/GovTech/SAMPLE/clean/final

---
Python warning:

2017-08-03T10:52:44	1	warning:C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\PyQt4\uic\uiparser.py:844: PendingDeprecationWarning: This method will be removed in future versions.  Use 'elem.iter()' or 'list(elem.iter())' instead.
			  for include in elem.getiterator("include"):
			
			traceback:  File "<string>", line 1, in <module>
			  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 333, in startPlugin
			    plugins[packageName] = package.classFactory(iface)
			  File "C:/Users/ganesh/.qgis2/python/plugins\networks\__init__.py", line 26, in classFactory
			    from reseaux import reseaux
			  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "C:/Users/ganesh/.qgis2/python/plugins\networks\reseaux.py", line 41, in <module>
			    import processing
			  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python/plugins\processing\__init__.py", line 29, in <module>
			    from processing.tools.general import *              # NOQA
			  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python/plugins\processing\tools\general.py", line 31, in <module>
			    from processing.core.Processing import Processing
			  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python/plugins\processing\core\Processing.py", line 46, in <module>
			    from processing.gui.MessageBarProgress import MessageBarProgress
			  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python/plugins\processing\gui\MessageBarProgress.py", line 32, in <module>
			    from processing.gui.MessageDialog import MessageDialog
			  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python/plugins\processing\gui\MessageDialog.py", line 38, in <module>
			    os.path.join(pluginPath, 'ui', 'DlgMessage.ui'))
			  File "C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\PyQt4\uic\__init__.py", line 210, in loadUiType
			    winfo = compiler.UICompiler().compileUi(uifile, code_string, from_imports, resource_suffix)
			  File "C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\PyQt4\uic\Compiler\compiler.py", line 139, in compileUi
			    w = self.parse(input_stream, resource_suffix)
			  File "C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\PyQt4\uic\uiparser.py", line 933, in parse
			    actor(elem)
			  File "C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\PyQt4\uic\uiparser.py", line 844, in readResources
			    for include in elem.getiterator("include"):
			
2017-08-03T10:52:45	1	warning:C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python\qgis\utils.py:607: ImportWarning: Not importing directory 'C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\win32\test': missing __init__.py
			  mod = _builtin_import(name, globals, locals, fromlist, level)
			
			traceback:  File "<string>", line 1, in <module>
			  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 333, in startPlugin
			    plugins[packageName] = package.classFactory(iface)
			  File "C:/Users/ganesh/.qgis2/python/plugins\networks\__init__.py", line 26, in classFactory
			    from reseaux import reseaux
			  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "C:/Users/ganesh/.qgis2/python/plugins\networks\reseaux.py", line 41, in <module>
			    import processing
			  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python/plugins\processing\__init__.py", line 29, in <module>
			    from processing.tools.general import *              # NOQA
			  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python/plugins\processing\tools\general.py", line 31, in <module>
			    from processing.core.Processing import Processing
			  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python/plugins\processing\core\Processing.py", line 62, in <module>
			    from processing.algs.saga.SagaAlgorithmProvider import SagaAlgorithmProvider
			  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python/plugins\processing\algs\saga\SagaAlgorithmProvider.py", line 33, in <module>
			    from SagaAlgorithm import SagaAlgorithm
			  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python/plugins\processing\algs\saga\SagaAlgorithm.py", line 20, in <module>
			    standard_library.install_aliases()
			  File "C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\future\standard_library\__init__.py", line 483, in install_aliases
			    import test
			
2017-08-03T10:53:15	1	warning:C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\xml\etree\ElementTree.py:1627: DeprecationWarning: This method of XMLParser is deprecated.  Define doctype() method on the TreeBuilder target.
			  DeprecationWarning,
			
			traceback:  File "C:/Users/ganesh/.qgis2/python/plugins\QgisGeopackage\qgis_geopackage.py", line 156, in write
			    gpkg.write(project_path)
			  File "C:/Users/ganesh/.qgis2/python/plugins\QgisGeopackage\qgpkg_qgis.py", line 33, in write
			    xmltree = self.read_project(project_path)
			  File "C:/Users/ganesh/.qgis2/python/plugins\QgisGeopackage\qgpkg_qgis.py", line 220, in read_project
			    return ET.parse(path)
			  File "C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\xml\etree\ElementTree.py", line 1182, in parse
			    tree.parse(source, parser)
			  File "C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\xml\etree\ElementTree.py", line 656, in parse
			    parser.feed(data)
			  File "C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\xml\etree\ElementTree.py", line 1640, in feed
			    self._parser.Parse(data, 0)
			  File "..\Modules\pyexpat.c", line 839, in DefaultHandlerExpand
			  File "C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\xml\etree\ElementTree.py", line 1611, in _default
			    self._XMLParser__doctype(name, pubid, system[1:-1])
			
---
Python Error

2017-08-03T10:53:15	1	Traceback (most recent call last):
			  File "C:/Users/ganesh/.qgis2/python/plugins\QgisGeopackage\qgis_geopackage.py", line 156, in write
			    gpkg.write(project_path)
			  File "C:/Users/ganesh/.qgis2/python/plugins\QgisGeopackage\qgpkg_qgis.py", line 120, in write
			    if reply:
			NameError: global name 'reply' is not defined

**Comment by pka** [comment]
The error was triggered when overwriting an existing project resource (e.g. image). This is fixed in 0.3.1.
Thanks for the detailed report!
