### ISSUE TITLE
no such table gpkg_extensions

### ISSUE THREAD

**Issue by pvgenuchten** [pka/qgpkg#5]
when writing the project to geopackage I get an error

Traceback (most recent call last):
  File ".qgis2/python/plugins\QgisGeopackage\qgis_geopackage.py", line 112, in write
    gpkg.write(project_path)
  File ".qgis2/python/plugins\QgisGeopackage\qgpkg.py", line 208, in write
    'INSERT INTO gpkg_extensions VALUES (?,?,?,?,?)', extensions)
OperationalError: no such table: gpkg_extensions

Maybe the plugin should create this table if it detects it is not available?

**Comment by pvgenuchten** [comment]
Fixed in 9c00ad6
